### ISSUE TITLE
Error Due to Random JWT Key Assignment

### ISSUE THREAD

**Issue by illusion069** [Kzsanjeet/PetAdaption#41]
While testing as a business analyst, I found a problem caused by randomly assigning the JWT key instead of putting it securely in the .env file. Because of this mistake, the system couldn't generate tokens properly, and it didn't work right.

**Comment by Kzsanjeet** [comment]
I observe my code and found the problem regarding the jwt secret key and solved that issue

**Comment by Kzsanjeet** [comment]
solved properly
