### ISSUE TITLE
Missing Delete Button for Shelter-home

### ISSUE THREAD

**Issue by illusion069** [Kzsanjeet/PetAdaption#53]
During testing, I found that the system does not have a delete button for shelter-home entries.

**Comment by SONAM56** [comment]
To address the issue of the missing delete button for shelter-home entries, l implements a feature enhancement to add the necessary functionality. The solution involves incorporating a delete button within the shelter-home entry interface, allowing users with the appropriate permissions to remove unwanted entries from the system. This delete button will be prominently displayed alongside each shelter-home entry, providing users with a straightforward method to delete entries as needed.
