### ISSUE TITLE
 Admin Unable to View Customer Feedback

### ISSUE THREAD

**Issue by illusion069** [Kzsanjeet/PetAdaption#54]
During testing, it was discovered that the admin is unable to view the feedback provided by customers.

**Comment by SONAM56** [comment]
To resolve the issue of the admin being unable to view customer feedback, I implement a feature enhancement in the admin panel. The solution involves adding a dedicated section within the admin dashboard specifically for viewing customer feedback. This section will display all feedback submitted by customers, along with relevant details such as the date and time of submission

**Comment by SONAM56** [comment]
To resolve the issue of the admin being unable to view customer feedback, I implement a feature enhancement in the admin panel. The solution involves adding a dedicated section within the admin dashboard specifically for viewing customer feedback. This section will display all feedback submitted by customers, along with relevant details such as the date and time of submission
