### ISSUE TITLE
Missing Phone Number Field When Adding Shelter

### ISSUE THREAD

**Issue by illusion069** [Kzsanjeet/PetAdaption#55]
During testing, I found that there is no field to enter a phone number when adding a new shelter. Without this field, users cannot provide a contact number, which is important for communication and coordination.

**Comment by SONAM56** [comment]
To address the issue of missing phone number field when adding a new shelter, I implement an update to the user interface. The solution involves adding a dedicated input field for users to enter their phone number during the process of adding a new shelter. I ensure that users have the necessary means to provide their contact information, facilitating effective communication and coordination
